#!/usr/bin/env python3
"""Exact finite inputs to the degree-eight extension (standard library only).

Run from any directory with Python 3. No files are written.
The manuscript supplies the all-orders versality, topology, period, and
global deformation proofs; this checks their printed lattice inputs.
"""

from fractions import Fraction
from itertools import permutations
import json
from math import gcd, prod


def determinant(rows):
    n = len(rows)
    return sum(
        (-1) ** sum(p[i] > p[j] for i in range(n) for j in range(i + 1, n))
        * prod(rows[i][p[i]] for i in range(n))
        for p in permutations(range(n))
    )


def main():
    polygon = {(1, 0), (0, 1), (-1, 0), (0, -1)}
    a, b = (1, 1), (1, -1)
    translated = {(x + 1, y) for x, y in polygon}
    assert translated == {(i * a[0] + j * b[0], i * a[1] + j * b[1])
                          for i in (0, 1) for j in (0, 1)}

    rays = [(0, 0, 1, 0), (1, 1, 1, 0),
            (0, 0, 0, 1), (1, -1, 0, 1)]
    index = abs(determinant(rays))
    assert index == 2
    half_sum = [Fraction(sum(r[i] for r in rays), 2) for i in range(4)]
    assert all(x.denominator == 1 for x in half_sum)
    assert half_sum == [1, 0, 1, 1]
    # In the ray basis this generator has all coefficients 1/2:
    # the unique nontrivial quotient element negates all four coordinates.
    projection_exponents = [[r[i] for r in rays] for i in (2, 3)]
    assert projection_exponents == [[1, 1, 0, 0], [0, 0, 1, 1]]
    assert (-1) ** 4 == 1  # The quotient action preserves the volume form.

    # The link circle bundle has Euler pairing (-2,-2). Its kernel is
    # generated by the ruling difference and its cokernel is Z/2.
    euler_pairing = (-2, -2)
    root = (1, -1)
    assert sum(x * y for x, y in zip(euler_pairing, root)) == 0
    assert 2 * root[0] * root[1] == -2
    link_fundamental_group_order = gcd(*euler_pairing)
    assert link_fundamental_group_order == 2

    result = {
        "cayley_rays": rays,
        "ray_lattice_index": index,
        "half_sum": [int(x) for x in half_sum],
        "projection_monomial_exponents": projection_exponents,
        "quotient_action_weights_mod_2": [1, 1, 1, 1],
        "link_euler_pairing": euler_pairing,
        "ruling_difference": root,
        "link_fundamental_group_order": link_fundamental_group_order,
        "quotient_period_multiplier": str(Fraction(1, index)),
        "scope": "Finite lattice inputs only; analytic and topological proofs are in the paper.",
    }
    print(json.dumps(result, indent=2))
    print("PASS: degree-eight Cayley quotient, parameter monomials, and link lattice")


if __name__ == "__main__":
    main()
