#!/usr/bin/env python3
"""Exact finite inputs to the degree-five extension (standard library only).

Run from any directory with Python 3. The script writes no files.
It prints the intersection data, Schubert computations, Chern calculation,
and exterior-product matrices used in the paper. Analytic versality,
boundary periods, and global deformation arguments require their proofs
in the manuscript; they are not established by these finite checks.
"""

from fractions import Fraction
from itertools import combinations, product
import json
from math import comb


def intersection(a, b):
    """Intersection in the ordered basis h,e1,e2,e3,e4."""
    return a[0] * b[0] - sum(a[i] * b[i] for i in range(1, 5))


def lattice_coordinates(gamma):
    """K-perpendicular class -> the five conic-pencil pairings."""
    x, *ys = gamma
    return tuple(x + y for y in ys) + (-x,)


def inverse_coordinates(lambdas):
    assert sum(lambdas) == 0
    return (-lambdas[4],) + tuple(lambdas[i] + lambdas[4]
                                 for i in range(4))


def reflected(gamma, root):
    pairing = intersection(gamma, root)
    return tuple(x + pairing * a for x, a in zip(gamma, root))


def permutation_group(generators):
    """Enumerate the subgroup generated by permutations of five labels."""
    identity = tuple(range(5))
    group = {identity}
    pending = [identity]
    while pending:
        old = pending.pop()
        for generator in generators:
            new = tuple(generator[old[i]] for i in range(5))
            if new not in group:
                group.add(new)
                pending.append(new)
    return group


def check_lattice():
    canonical = (-3, 1, 1, 1, 1)
    pencils = [(1,) + tuple(-int(j == i) for j in range(4))
               for i in range(4)] + [(2, -1, -1, -1, -1)]
    roots = [(0, 1, -1, 0, 0), (0, 0, 1, -1, 0),
             (0, 0, 0, 1, -1), (1, -1, -1, -1, 0)]

    assert intersection(canonical, canonical) == 5
    pencil_matrix = [[intersection(a, b) for b in pencils]
                     for a in pencils]
    assert pencil_matrix == [[int(i != j) for j in range(5)]
                             for i in range(5)]
    assert all(intersection(canonical, f) == -2 for f in pencils)
    assert tuple(sum(f[j] for f in pencils) for j in range(5)) == \
        tuple(-2 * k for k in canonical)

    root_gram = [[intersection(a, b) for b in roots] for a in roots]
    assert root_gram == [[-2 if i == j else int(abs(i - j) == 1)
                         for j in range(4)] for i in range(4)]
    for i, root in enumerate(roots):
        assert intersection(root, canonical) == 0
        assert lattice_coordinates(root) == \
            tuple(int(j == i) - int(j == i + 1) for j in range(5))

    # The quadratic Cremona transformation is reflection in the last root.
    cremona = roots[-1]
    cremona_permutation = (0, 1, 2, 4, 3)
    for i, pencil in enumerate(pencils):
        assert reflected(pencil, cremona) == pencils[cremona_permutation[i]]
    basis = [tuple(int(i == j) for i in range(5)) for j in range(5)]
    cremona_columns = [reflected(v, cremona) for v in basis]
    cremona_matrix = [list(row) for row in zip(*cremona_columns)]
    assert reflected(canonical, cremona) == canonical

    generators = []
    for i in range(3):
        permutation = list(range(5))
        permutation[i], permutation[i + 1] = permutation[i + 1], permutation[i]
        generators.append(tuple(permutation))
    generators.append(cremona_permutation)
    assert len(permutation_group(generators)) == 120

    replay_count = 0
    for first_four in product(range(-2, 3), repeat=4):
        lambdas = first_four + (-sum(first_four),)
        gamma = inverse_coordinates(lambdas)
        assert intersection(gamma, canonical) == 0
        assert lattice_coordinates(gamma) == lambdas
        assert tuple(intersection(gamma, f) for f in pencils) == lambdas
        assert intersection(gamma, gamma) == -sum(x * x for x in lambdas)
        assert lattice_coordinates(reflected(gamma, cremona)) == \
            tuple(lambdas[cremona_permutation[i]] for i in range(5))
        replay_count += 1
    assert replay_count == 625

    return {
        "basis": ["h", "e1", "e2", "e3", "e4"],
        "canonical_class": canonical,
        "five_pencil_classes": pencils,
        "pencil_intersection_matrix": pencil_matrix,
        "A4_simple_roots": roots,
        "negative_A4_Gram_matrix": root_gram,
        "coordinates": "lambda_i=x+y_i (i<=4), lambda_5=-x; sum(lambda_i)=0",
        "inverse": "x=-lambda_5, y_i=lambda_i+lambda_5",
        "cremona_matrix_acting_on_columns": cremona_matrix,
        "cremona_pencil_permutation_one_based": [i + 1 for i in cremona_permutation],
        "generated_pencil_permutation_group_order": 120,
        "integral_coordinate_vectors_replayed": replay_count,
    }


# Schubert classes of Gr(2,5), in the 2-by-3 rectangle. The empty
# partition is the unit; (3,3) is the class of a point.
PARTITIONS = tuple((a, b) for a in range(4) for b in range(a + 1))


def pieri(schubert, strip_size, vertical=False):
    """Multiply by a row or column Schubert class using the Pieri rule."""
    result = {}
    for old, coefficient in schubert.items():
        for new in PARTITIONS:
            if any(new[i] < old[i] for i in range(2)):
                continue
            if sum(new) - sum(old) != strip_size:
                continue
            if vertical:
                allowed = all(new[i] - old[i] <= 1 for i in range(2))
            else:
                # A horizontal strip has at most one new box per column.
                allowed = new[0] >= old[0] >= new[1] >= old[1]
            if allowed:
                result[new] = result.get(new, 0) + coefficient
    return result


def multiply_by_H(schubert, exponent):
    for _ in range(exponent):
        schubert = pieri(schubert, 1)
    return schubert


def schubert_json(schubert):
    return {str(partition): coefficient
            for partition, coefficient in sorted(schubert.items())}


# Polynomials in the formal Chern roots x,y, truncated in total degree 3.
MAX_CHERN_DEGREE = 3
ONE = {(0, 0): 1}
X = {(1, 0): 1}
Y = {(0, 1): 1}


def poly_add(*polynomials):
    result = {}
    for polynomial in polynomials:
        for exponent, coefficient in polynomial.items():
            result[exponent] = result.get(exponent, 0) + coefficient
    return {exponent: coefficient for exponent, coefficient in result.items()
            if coefficient}


def poly_scale(polynomial, scalar):
    return {exponent: coefficient * scalar
            for exponent, coefficient in polynomial.items() if coefficient * scalar}


def poly_multiply(a, b):
    result = {}
    for left, left_coefficient in a.items():
        for right, right_coefficient in b.items():
            exponent = tuple(left[i] + right[i] for i in range(2))
            if sum(exponent) <= MAX_CHERN_DEGREE:
                result[exponent] = result.get(exponent, 0) + \
                    left_coefficient * right_coefficient
    return {exponent: coefficient for exponent, coefficient in result.items()
            if coefficient}


def poly_power(polynomial, exponent):
    result = ONE
    for _ in range(exponent):
        result = poly_multiply(result, polynomial)
    return result


def homogeneous(polynomial, degree):
    return {exponent: coefficient for exponent, coefficient in polynomial.items()
            if sum(exponent) == degree}


def polynomial_json(polynomial):
    return {f"x^{i} y^{j}": coefficient
            for (i, j), coefficient in sorted(polynomial.items(), reverse=True)}


def check_schubert_and_chern():
    unit = {(0, 0): 1}
    H_squared = multiply_by_H(unit, 2)
    P = pieri(unit, 2, vertical=True)  # c2(S*) = sigma_(1,1)
    assert H_squared == {(2, 0): 1, (1, 1): 1}
    assert P == {(1, 1): 1}
    assert pieri(unit, 2) == {(2, 0): 1}

    H_powers = [multiply_by_H(unit, power) for power in range(7)]
    H_four_P = multiply_by_H(P, 4)
    assert H_powers[6] == {(3, 3): 5}
    assert H_four_P == {(3, 3): 2}

    # If x,y are the roots of S*, then H=x+y and P=xy. In K-theory,
    # TGr=S* tensor Q=5S*-(S* tensor S). The four roots of S* tensor S
    # are 0,0,x-y,y-x. Therefore
    # c(TGr)=(1+x)^5(1+y)^5 / (1-(x-y)^2).
    H = poly_add(X, Y)
    P_polynomial = poly_multiply(X, Y)
    difference = poly_add(X, poly_scale(Y, -1))
    numerator = poly_multiply(poly_power(poly_add(ONE, X), 5),
                              poly_power(poly_add(ONE, Y), 5))
    inverse_endomorphism_class = poly_add(ONE, poly_power(difference, 2))
    grassmannian_chern = poly_multiply(numerator, inverse_endomorphism_class)
    expected_gr = [poly_scale(H, 5),
                   poly_add(poly_scale(poly_power(H, 2), 11), P_polynomial),
                   poly_scale(poly_power(H, 3), 15)]
    for degree, expected in enumerate(expected_gr, 1):
        assert homogeneous(grassmannian_chern, degree) == expected

    # V5 is a smooth intersection of three Pluecker hyperplanes.
    # Its normal bundle is O(H)^3, so divide by (1+H)^3.
    inverse_normal = poly_add(*(poly_scale(poly_power(H, degree),
                                           (-1) ** degree * comb(degree + 2, 2))
                                for degree in range(4)))
    threefold_chern = poly_multiply(grassmannian_chern, inverse_normal)
    expected_v = [poly_scale(H, 2),
                  poly_add(poly_scale(poly_power(H, 2), 2), P_polynomial),
                  poly_add(poly_scale(poly_power(H, 3), 2),
                           poly_scale(poly_multiply(H, P_polynomial), -3))]
    for degree, expected in enumerate(expected_v, 1):
        assert homogeneous(threefold_chern, degree) == expected
    assert homogeneous(threefold_chern, 3) == \
        {(3, 0): 2, (2, 1): 3, (1, 2): 3, (0, 3): 2}

    # Push forward c3(TV) along the codimension-three linear inclusion.
    euler_characteristic = 2 * H_powers[6][(3, 3)] - 3 * H_four_P[(3, 3)]
    assert euler_characteristic == 4
    return {
        "H": "sigma_(1,0) = c1(S*)",
        "P": "sigma_(1,1) = c2(S*)",
        "Pieri_H_powers_0_through_6": [schubert_json(value) for value in H_powers],
        "Pieri_H_four_P": schubert_json(H_four_P),
        "integral_Gr_H_six": H_powers[6][(3, 3)],
        "integral_Gr_H_four_P": H_four_P[(3, 3)],
        "grassmannian_Chern_classes": ["5H", "11H^2+P", "15H^3"],
        "V5_Chern_classes": ["2H", "2H^2+P", "2H^3-3HP"],
        "V5_c3_in_formal_roots": polynomial_json(homogeneous(threefold_chern, 3)),
        "V5_Euler_characteristic": euler_characteristic,
    }


def rational_rank(matrix):
    rows = [[Fraction(entry) for entry in row] for row in matrix]
    pivot_row = 0
    for column in range(len(rows[0])):
        pivot = next((i for i in range(pivot_row, len(rows))
                      if rows[i][column]), None)
        if pivot is None:
            continue
        rows[pivot_row], rows[pivot] = rows[pivot], rows[pivot_row]
        scale = rows[pivot_row][column]
        rows[pivot_row] = [entry / scale for entry in rows[pivot_row]]
        for i in range(len(rows)):
            if i != pivot_row and rows[i][column]:
                scale = rows[i][column]
                rows[i] = [a - scale * b
                           for a, b in zip(rows[i], rows[pivot_row])]
        pivot_row += 1
        if pivot_row == len(rows):
            break
    return pivot_row


def exterior_product_sign(left, right):
    if set(left) & set(right):
        return 0
    inversions = sum(a > b for a in left for b in right)
    return (-1) ** inversions


def wedge_matrix(two_form, pair_basis, four_basis):
    row_of = {indices: row for row, indices in enumerate(four_basis)}
    matrix = [[0 for _ in pair_basis] for _ in four_basis]
    for column, pair in enumerate(pair_basis):
        for indices, coefficient in two_form.items():
            sign = exterior_product_sign(indices, pair)
            if sign:
                row = row_of[tuple(sorted(indices + pair))]
                matrix[row][column] += sign * coefficient
    return matrix


def skew_matrix(two_form):
    matrix = [[0 for _ in range(5)] for _ in range(5)]
    for (i, j), coefficient in two_form.items():
        matrix[i - 1][j - 1] = coefficient
        matrix[j - 1][i - 1] = -coefficient
    return matrix


def check_exterior_products():
    pair_basis = tuple(combinations(range(1, 6), 2))
    four_basis = tuple(combinations(range(1, 6), 4))
    rank_two_form = {(1, 2): 1}
    rank_four_form = {(1, 2): 1, (3, 4): 1}
    rank_two_wedge = wedge_matrix(rank_two_form, pair_basis, four_basis)
    rank_four_wedge = wedge_matrix(rank_four_form, pair_basis, four_basis)
    assert rational_rank(skew_matrix(rank_two_form)) == 2
    assert rational_rank(skew_matrix(rank_four_form)) == 4
    assert rational_rank(rank_two_wedge) == 3
    assert rational_rank(rank_four_wedge) == 5
    return {
        "map": "Lambda^2(C^5) -> Lambda^4(C^5), eta -> xi wedge eta",
        "column_basis": pair_basis,
        "row_basis": four_basis,
        "rank_two_normal_form": "xi=e1 wedge e2",
        "rank_two_wedge_matrix": rank_two_wedge,
        "rank_two_wedge_map_rank": rational_rank(rank_two_wedge),
        "rank_four_normal_form": "xi=e1 wedge e2 + e3 wedge e4",
        "rank_four_wedge_matrix": rank_four_wedge,
        "rank_four_wedge_map_rank": rational_rank(rank_four_wedge),
    }


def main():
    result = {
        "degree_five_lattice": check_lattice(),
        "Grassmannian_and_V5": check_schubert_and_chern(),
        "exterior_product_normal_forms": check_exterior_products(),
        "scope": "Exact finite inputs only; analytic and global proofs are in the paper.",
    }
    print(json.dumps(result, indent=2))
    print("PASS: degree-five lattice, five pencils, Pieri integrals, V5 Chern classes, "
          "and exterior-product ranks")


if __name__ == "__main__":
    main()
