#!/usr/bin/env python3
"""Sing(X_9) is exactly the three germ points.

smoothing.md invokes this as "the standard Batyrev statement".  It is, but it
has a hypothesis, and the hypothesis is checkable, so it is checked here
rather than assumed.

For a reflexive Delta and the generic (Delta-regular) anticanonical
X subset P_Delta:

  * X meets the orbit O(sigma) iff dim sigma <= 3; over a 3-dimensional cone
    -- a 2-face F -- it meets the 1-dimensional orbit in l(F^o) points, and
    the germ there is the cone over the surface of F;
  * X is smooth wherever P_Delta is, because X is Delta-regular;
  * so Sing(X) sits over the 2-faces whose cone is singular, PROVIDED
    P_Delta is smooth along the orbits of the cones of dimension 1 and 2, and
    PROVIDED X misses the torus-fixed points.

Both provisos are verified below.

  Dimension 1.  A ray generated by a primitive vector is a smooth cone.
  Dimension 2.  The cone over an EDGE {v,w} of Delta is smooth exactly when
    {v,w} is a Z-basis of span(v,w) cap Z^4, i.e. when the 2x4 matrix has
    unit gcd of 2x2 minors.  With all edges of Delta unit this always holds:
    for a facet functional u with <u,v> = <u,w> = 1 and w-v primitive, any
    lattice point x = av + bw has <u,x> = a+b in Z and x - <u,x>v = b(w-v),
    so b in Z and then a in Z.  The check below confirms it directly.
  Dimension 4.  The generic anticanonical section is nonzero at the fixed
    point of a maximal cone sigma, because the monomial of the polar vertex
    u_sigma of Delta^o survives there and its coefficient is generic.

Run:  python3 sing_locus.py     (from paper5/)
"""
import itertools
import json
import os
import sys
from fractions import Fraction as Fr

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "src"))
sys.path.insert(0, os.path.join(HERE, "..", "..", "paper4", "certificates"))
from batyrev_global import (facets, two_faces, face_lattice_polygon,   # noqa
                            classify_polygon, dual_edge_length, vgcd, dot)
from examples import polar                                            # noqa

CHECKS = [0]
def ok(label, cond):
    CHECKS[0] += 1
    print(f"  [{'ok ' if cond else 'FAIL'}] {label}")
    assert cond, label

def minors2(v, w):
    return [v[i] * w[j] - v[j] * w[i] for i, j in itertools.combinations(range(4), 2)]

V = [tuple(v) for v in json.load(open(os.path.join(HERE, "v09_candidate.json")))["V"]]
facs = facets(V)
print(f"Delta_9: {len(V)} vertices, {len(facs)} facets")

print("\n== dimension 1: the rays ==")
ok("every vertex of Delta_9 is a primitive lattice vector, so every ray of "
   "the face fan is a smooth cone", all(vgcd(v) == 1 for v in V))

print("\n== dimension 2: the cones over the edges ==")
tfs = [(sorted(I), fp) for I, fp in two_faces(V, facs)]
edges = set()
for A, _ in tfs:
    for B, _ in tfs:
        if A is B:
            continue
        c = tuple(sorted(set(A) & set(B)))
        if len(c) == 2:
            edges.add(c)
edges = sorted(edges)
print(f"    {len(edges)} edges")
ok("every edge of Delta_9 has lattice length one",
   all(vgcd(tuple(V[b][k] - V[a][k] for k in range(4))) == 1 for a, b in edges))
bad = [(a, b) for a, b in edges if vgcd(tuple(minors2(V[a], V[b]))) != 1]
ok(f"every edge cone is SMOOTH: the 2x2 minors of (v,w) have unit gcd "
   f"({len(bad)} failures)", not bad)
print("    => P_Delta is smooth along the orbits of all cones of dimension <= 2,")
print("       so X_9 is smooth there, being Delta-regular")

print("\n== dimension 3: the 2-faces ==")
sing = []
for I, fp in tfs:
    _, evs, lens = face_lattice_polygon(V, frozenset(I), facs[fp[0]][0], facs[fp[1]][0])
    cl = classify_polygon(evs, lens)
    dl = dual_edge_length(facs[fp[0]][0], facs[fp[1]][0])
    if cl["status"] != "smooth":
        sing.append((I, cl["k"], dl))
print(f"    {len(tfs)} two-faces, {len(sing)} with a singular cone:")
for I, k, dl in sing:
    print(f"      {I}: {'square (node)' if k == 4 else 'pentagon (dP7)'}, "
          f"{dl} point(s) on X_9")
ok("exactly three 2-faces have a singular cone, each carrying one point",
   len(sing) == 3 and all(dl == 1 for _, _, dl in sing))

print("\n== dimension 4: the fixed points ==")
P = polar(V)
lo = [min(p[i] for p in P) for i in range(4)]
hi = [max(p[i] for p in P) for i in range(4)]
facsP = facets(P)
lat = set()
for x in itertools.product(*[range(lo[i], hi[i] + 1) for i in range(4)]):
    if all(dot(u, x) <= c for u, c, _ in facsP):
        lat.add(x)
ok(f"the polar has {len(lat)} lattice points, and every polar VERTEX is one "
   "of them", all(tuple(p) in lat for p in P))
ok("so for each maximal cone sigma the monomial of its polar vertex "
   "u_sigma appears in the anticanonical system; a generic section has "
   "nonzero coefficient there, hence does not vanish at the fixed point of "
   "sigma, and X_9 misses every torus-fixed point", len(P) == len(facs))

print(f"\n{CHECKS[0]} checks passed.")
print("""
CONCLUSION.  P_Delta is smooth along every orbit of a cone of dimension at
most two; X_9 misses the fixed points; and of the 2-faces exactly three have a
singular cone, each contributing one point.  So

        Sing(X_9) = two nodes and one dP7 point, and nothing else,

which is what smoothing.md step 3 needs.""")
